server:
  port: 8084

spring:
  application:
    name: APIGATEWAY


  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/users/getAllUsers/**, /api/users/create/**, /api/users/{userId}/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/api/hotels/getAllHotels/**, /api/hotels/create/**, /api/hotels/{hotelId}/**

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/api/rating/getAllRating/**, /api/rating/create/**, /api/rating/users/{userId}/**, /api/rating/hotel/{hotelId}/**, /api/rating/update/{ratingId}/**, /api/rating/delete/{ratingId}/**




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
