server:
  port: 8084

spring:
  application:
    name: APIGATEWAY


  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/users/getAllUsers/**, /api/users/create/**, /api/users/{userId}/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/api/hotels/getAllHotels/**, /api/hotels/create/**, /api/hotels/{hotelId}/**

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/api/rating/getAllRating/**, /api/rating/create/**, /api/rating/users/{userId}/**, /api/rating/hotel/{hotelId}/**, /api/rating/update/{ratingId}/**, /api/rating/delete/{ratingId}/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# okta configuration for api gateways
okta:
  oauth2:
    issuer: https://dev-52077336.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaoq27p59OyUXZ085d7
    client-secret: q1uaFp1bhG2FlZFS98XGgak6l-yLP0FXijtIQj4Y_pgeQZhkO8a5gRw8XWVMybRG
    scopes: openid, profile, email, offline_access
